// <auto-generated />
using System;
using BeanScene.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeanScene.Web.Migrations
{
    [DbContext(typeof(BeanSceneContext))]
    [Migration("20251124062401_DropIsClosedFromSitting")]
    partial class DropIsClosedFromSitting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeanScene.Web.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AreaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("AreaId")
                        .HasName("PK__Area__70B82028FEDCE2CC");

                    b.HasIndex(new[] { "AreaName" }, "UQ__Area__8EB6AF57AFF687E8")
                        .IsUnique();

                    b.ToTable("Area", (string)null);
                });

            modelBuilder.Entity("BeanScene.Web.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReservationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ReservationSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SittingId")
                        .HasColumnType("int")
                        .HasColumnName("SittingID");

                    b.Property<DateTime>("StartTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ReservationId")
                        .HasName("PK__Reservat__B7EE5F0404326B6B");

                    b.HasIndex(new[] { "SittingId", "StartTime" }, "IX_Reservation_Sitting_Start");

                    b.HasIndex(new[] { "Status" }, "IX_Reservation_Status");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("BeanScene.Web.Models.ReservationTable", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("ReservationID");

                    b.Property<int>("RestaurantTableID")
                        .HasColumnType("int")
                        .HasColumnName("RestaurantTableID");

                    b.HasKey("ReservationId", "RestaurantTableID");

                    b.HasIndex("RestaurantTableID");

                    b.ToTable("ReservationTable", (string)null);
                });

            modelBuilder.Entity("BeanScene.Web.Models.RestaurantTable", b =>
                {
                    b.Property<int>("RestaurantTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RestaurantTableID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantTableId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("AreaID");

                    b.Property<int?>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("RestaurantTableId")
                        .HasName("PK__Restaura__15D937BA28FD3CE3");

                    b.HasIndex(new[] { "AreaId", "TableName" }, "UQ_Area_Table")
                        .IsUnique();

                    b.ToTable("RestaurantTable", (string)null);
                });

            modelBuilder.Entity("BeanScene.Web.Models.SittingSchedule", b =>
                {
                    b.Property<int>("SittingScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SittingScheduleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SittingScheduleId"));

                    b.Property<DateTime>("EndDateTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("Scapacity")
                        .HasColumnType("int")
                        .HasColumnName("SCapacity");

                    b.Property<DateTime>("StartDateTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Stype")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SType");

                    b.HasKey("SittingScheduleId")
                        .HasName("PK__SittingS__AE09170F976F16D2");

                    b.HasIndex(new[] { "Stype", "StartDateTime", "EndDateTime" }, "UQ_Sitting_Window")
                        .IsUnique();

                    b.ToTable("SittingSchedule", (string)null);
                });

            modelBuilder.Entity("BeanScene.Web.Models.Reservation", b =>
                {
                    b.HasOne("BeanScene.Web.Models.SittingSchedule", "Sitting")
                        .WithMany("Reservations")
                        .HasForeignKey("SittingId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservation_Sitting");

                    b.Navigation("Sitting");
                });

            modelBuilder.Entity("BeanScene.Web.Models.ReservationTable", b =>
                {
                    b.HasOne("BeanScene.Web.Models.Reservation", "Reservation")
                        .WithMany("ReservationTables")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReservationTable_Reservation");

                    b.HasOne("BeanScene.Web.Models.RestaurantTable", "RestaurantTable")
                        .WithMany("ReservationTables")
                        .HasForeignKey("RestaurantTableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReservationTable_Table");

                    b.Navigation("Reservation");

                    b.Navigation("RestaurantTable");
                });

            modelBuilder.Entity("BeanScene.Web.Models.RestaurantTable", b =>
                {
                    b.HasOne("BeanScene.Web.Models.Area", "Area")
                        .WithMany("RestaurantTables")
                        .HasForeignKey("AreaId")
                        .IsRequired()
                        .HasConstraintName("FK_Table_Area");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("BeanScene.Web.Models.Area", b =>
                {
                    b.Navigation("RestaurantTables");
                });

            modelBuilder.Entity("BeanScene.Web.Models.Reservation", b =>
                {
                    b.Navigation("ReservationTables");
                });

            modelBuilder.Entity("BeanScene.Web.Models.RestaurantTable", b =>
                {
                    b.Navigation("ReservationTables");
                });

            modelBuilder.Entity("BeanScene.Web.Models.SittingSchedule", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
